#!/usr/bin/env bash
#
#: exec_target = cli

## Build all or a single frontend component package.
##
## Usage: fin frontend/build [package_name|optional]

if [[ -n "$1" ]]; then
  corepack enable && yarn build:scope "$1"
else
  corepack enable && yarn build
fi
