<?php

/**
 * @file
 * Functions to support theming.
 */

/**
 * Load theme include files.
 */
foreach (glob(dirname(__FILE__) . '/includes/*.php') as $filename) {
  include_once $filename;
}

/**
 * Implements template_preprocess_paragraph().
 */
function ixm_preprocess_paragraph__hero(&$variables) {
  $paragraph = $variables['paragraph'];
  $parent_entity = $paragraph->getParentEntity();

  // If the parent is a node
  if ($parent_entity && $parent_entity->getEntityTypeId() === 'node') {
    // Set variable containing the node
    $node = $parent_entity;
    // Get the node title and expose as variable
    $variables['node_title'] = $node->getTitle();
  }
}

/**
 * Implements hook_preprocess_HOOK() for menu.html.twig.
 */
function ixm_preprocess_menu(&$variables) {
  if (isset($variables['menu_name'])) {
    $variables['attributes']['class'][] = 'menu--' . $variables['menu_name'];
  }
}
