#!/usr/bin/env bash

## Initialize stack and site
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Execution --------------------------------

# Remove this .git.
echo-yellow 'Resetting git.'
rm -rf .git
git init -b master

# Stack initialization
echo -e "${green_bg} Step 1 ${NC}${green} Resetting stack...${NC}"
fin project reset -f

# Install project requirements
echo-green 'Loading dependencies'
fin exec composer clear-cache --no-interaction
fin exec COMPOSER_PROCESS_TIMEOUT=2000
fin exec COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction

echo-green 'Setup Swat'
cd "$PROJECT_ROOT"
fin swat setup

echo-yellow 'Resetting container for host change.'
fin project reset -f
echo-green-bg 'ALL DONE! Setup your project configuration (swat/swat.yml) and then run swat setup:install'
